{% set name = "c3" %}
{% set version = "0.5.2" %}
{% set sha256 = "2696480287c13f1d2c80634c96f496107618461bf967fbcacbded78d6b88c36e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/c3js/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  run:
    - nodejs
    
test:
  commands:
    - npm list -g c3
    

about:
  home: https://github.com/c3js/c3
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A D3-based reusable chart library'
  description: |
    A D3-based reusable chart library   
  doc_url: http://c3js.org/gettingstarted.html
  dev_url: https://github.com/c3js/c3

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
